### PR TITLE
Simplify Symfony2 Composer configuration

### PR DESCRIPTION
**Pull request by David-Guillot**
No need for all dependencies, Composer is recursive, and I see your Symfony2 bundle is already requiring all Isolate components ;)

### CODE REVIEW

**Comment by norberttech** [comment]
I also thought so but composer by default ignores dev dependencies : / 
This behavior can be modified by changing [minimum stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) to dev (default is stable) but IMO it might make more harm to the projects than adding those 3 extra dependencies which is just temporary solution.

**Comment by norberttech** [comment]
But anyway I would like to keep this ticke open, its gonna remind me after 1.0.0 release that I need to remove those extra dependnecies from docs, thanks :beers:

**Comment by David-Guillot** [comment]
Ah yes I didn't remember this Composer behaviour (quite legit by the way)... Should have tested it on local before PRing :-P

**Comment by David-Guillot** [comment]
Closing this as the project doesn't seem maintained, and i'm doing some Github cleanup

**Comment by norberttech** [comment]
yeah, it's kind of dead now, sorry

**Pull request closed without merging**
